[dev]
  command = "yarn dev"
  targetPort=5173

[build]
	functions = "functions"

[functions]
	node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# [[redirects]]
# 	from = "/*"
# 	to = "/"
# 	status = 200
